services:
  db:
    image: postgres:15-alpine
    container_name: taxifun-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Mambou2025!}
      POSTGRES_DB: ${DB_NAME:-taxifun_db}
    healthcheck:
      # <--- AJOUTE CE BLOC ICI
      test: [ "CMD-SHELL", "pg_isready -U admin -d taxifun_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - taxifun_postgres_data:/var/lib/postgresql/data
    networks:
      - taxifun-network

  cache:
    image: redis:7-alpine
    container_name: taxifun-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - taxifun-network

  api:
    build: .
    container_name: taxifun-api
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy # Maintenant Ã§a va marcher !
      cache:
        condition: service_started
    networks:
      - taxifun-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: taxifun-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taxifun.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - taxifun-network

networks:
  taxifun-network:
    driver: bridge

volumes:
  taxifun_postgres_data:
