services:
  # Base de données
  db:
    image: postgres:15-alpine
    container_name: taxifun-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Mambou2025!}
      POSTGRES_DB: ${DB_NAME:-taxifun_db}
    ports:
      - "5432:5432"
    volumes:
      - taxifun_postgres_data:/var/lib/postgresql/data
    networks:
      - taxifun-network

  # Cache Redis
  cache:
    image: redis:7-alpine
    container_name: taxifun-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - taxifun-network

  # API NestJS
  api:
    build: .
    container_name: taxifun-api
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev # <--- ICI : On dit au Chef d'Orchestre de ne pas écouter le Dockerfile

    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db # <--- J'AI SIMPLIFIÉ ICI (Plus de condition "healthy")
      - cache # <--- ICI AUSSI
    networks:
      - taxifun-network

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: taxifun-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taxifun.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - taxifun-network

networks:
  taxifun-network:
    driver: bridge

volumes:
  taxifun_postgres_data:
